//tag::ref-doc[]
= Image Recognition Processor

A processor that uses an https://github.com/tensorflow/models/tree/master/inception[Inception model] to classify
in real-time images into different categories (e.g. labels).

Model implements a deep https://en.wikipedia.org/wiki/Convolutional_neural_network[Convolutional Neural Network] that can achieve reasonable performance on hard visual recognition tasks
- matching or exceeding human performance in some domains like https://www.tensorflow.org/tutorials/image_recognition[image recognition].

The input of the model is an image as binary array.

The output is a JSON message in this format:

```json
{
  "labels" : [
     {"giant panda":0.98649305}
  ]
}
```
Result contains the name of the recognized category (e.g. label) along with the confidence (e.g. confidence) that the image represents this category.

If the `response-seize` is set to value higher then 1, then the result will include the top `response-seize` probable labels. For example `response-size=3` would return:

```json
{
  "labels": [
    {"giant panda":0.98649305},
    {"badger":0.010562794},
    {"ice bear":0.001130851}
  ]
}
```

== Options

The **$$image-recognition$$** $$processor$$ has the following options:

//tag::configuration-properties[]
$$tensorflow.expression$$:: $$How to obtain the input data from the input message. If empty it defaults to the input message payload. The headers[myHeaderName] expression to get input data from message's header using myHeaderName as a key.$$ *($$Expression$$, default: `$$<none>$$`)*
$$tensorflow.image.recognition.draw-labels$$:: $$When set to true it augment the input image with the predicted labels$$ *($$Boolean$$, default: `$$true$$`)*
$$tensorflow.image.recognition.labels$$:: $$The text file containing the category names (e.g. labels) of all categories that this model is trained to recognize. Every category is on a separate line.$$ *($$Resource$$, default: `$$<none>$$`)*
$$tensorflow.image.recognition.response-size$$:: $$Number of top K alternatives to add to the result. Only used when the responseSize > 0.$$ *($$Integer$$, default: `$$1$$`)*
$$tensorflow.mode$$:: $$The outbound message can store the inference result either in the payload or in a header with name outputName. The payload mode (default) stores the inference result in the outbound message payload. The inbound payload is discarded. The header mode stores the inference result in outbound message's header defined by the outputName property. The the inbound message payload is passed through to the outbound such.$$ *($$OutputMode$$, default: `$$<none>$$`, possible values: `payload`,`header`)*
$$tensorflow.model$$:: $$The location of the pre-trained TensorFlow model file. The file, http and classpath schemas are supported. For archive locations takes the first file with '.pb' extension. Use the URI fragment parameter to specify an exact model name (e.g. https://foo/bar/model.tar.gz#frozen_inference_graph.pb)$$ *($$Resource$$, default: `$$<none>$$`)*
$$tensorflow.model-fetch$$:: $$The TensorFlow graph model outputs. Comma separate list of TensorFlow operation names to fetch the output Tensors from.$$ *($$List<String>$$, default: `$$<none>$$`)*
$$tensorflow.output-name$$:: $$The output data key used for the Header modes.$$ *($$String$$, default: `$$result$$`)*
//end::configuration-properties[]

//end::ref-doc[]
== Build

```
$> mvn package
```
