// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/string_int_label_map.proto

package org.springframework.cloud.stream.app.object.detection.protos;

public final class StringIntLabelMapOuterClass {
  private StringIntLabelMapOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StringIntLabelMapItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * String name. The most common practice is to set this to a MID or synsets id.
     * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
     * </pre>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * String name. The most common practice is to set this to a MID or synsets id.
     * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
     * </pre>
     */
    String getName();
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * String name. The most common practice is to set this to a MID or synsets id.
     * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
     * </pre>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Integer id that maps to the string name above. Label ids should start from 1.
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Integer id that maps to the string name above. Label ids should start from 1.
     * </pre>
     */
    int getId();

    /**
     * <code>optional string display_name = 3;</code>
     *
     * <pre>
     * Human readable string label.
     * </pre>
     */
    boolean hasDisplayName();
    /**
     * <code>optional string display_name = 3;</code>
     *
     * <pre>
     * Human readable string label.
     * </pre>
     */
    String getDisplayName();
    /**
     * <code>optional string display_name = 3;</code>
     *
     * <pre>
     * Human readable string label.
     * </pre>
     */
    com.google.protobuf.ByteString
        getDisplayNameBytes();
  }
  /**
   * Protobuf type {@code org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem}
   */
  public static final class StringIntLabelMapItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem)
      StringIntLabelMapItemOrBuilder {
    // Use StringIntLabelMapItem.newBuilder() to construct.
    private StringIntLabelMapItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StringIntLabelMapItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StringIntLabelMapItem defaultInstance;
    public static StringIntLabelMapItem getDefaultInstance() {
      return defaultInstance;
    }

    public StringIntLabelMapItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StringIntLabelMapItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              displayName_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StringIntLabelMapItem.class, Builder.class);
    }

    public static com.google.protobuf.Parser<StringIntLabelMapItem> PARSER =
        new com.google.protobuf.AbstractParser<StringIntLabelMapItem>() {
      public StringIntLabelMapItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringIntLabelMapItem(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<StringIntLabelMapItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * String name. The most common practice is to set this to a MID or synsets id.
     * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
     * </pre>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * String name. The most common practice is to set this to a MID or synsets id.
     * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
     * </pre>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     *
     * <pre>
     * String name. The most common practice is to set this to a MID or synsets id.
     * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Integer id that maps to the string name above. Label ids should start from 1.
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 id = 2;</code>
     *
     * <pre>
     * Integer id that maps to the string name above. Label ids should start from 1.
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int DISPLAY_NAME_FIELD_NUMBER = 3;
    private Object displayName_;
    /**
     * <code>optional string display_name = 3;</code>
     *
     * <pre>
     * Human readable string label.
     * </pre>
     */
    public boolean hasDisplayName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string display_name = 3;</code>
     *
     * <pre>
     * Human readable string label.
     * </pre>
     */
    public String getDisplayName() {
      Object ref = displayName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string display_name = 3;</code>
     *
     * <pre>
     * Human readable string label.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      Object ref = displayName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      displayName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDisplayNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDisplayNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static StringIntLabelMapItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StringIntLabelMapItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StringIntLabelMapItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StringIntLabelMapItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StringIntLabelMapItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static StringIntLabelMapItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static StringIntLabelMapItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static StringIntLabelMapItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static StringIntLabelMapItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static StringIntLabelMapItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(StringIntLabelMapItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem)
        StringIntLabelMapItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StringIntLabelMapItem.class, Builder.class);
      }

      // Construct using org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapOuterClass.StringIntLabelMapItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        displayName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_descriptor;
      }

      public StringIntLabelMapItem getDefaultInstanceForType() {
        return StringIntLabelMapItem.getDefaultInstance();
      }

      public StringIntLabelMapItem build() {
        StringIntLabelMapItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public StringIntLabelMapItem buildPartial() {
        StringIntLabelMapItem result = new StringIntLabelMapItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.displayName_ = displayName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StringIntLabelMapItem) {
          return mergeFrom((StringIntLabelMapItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StringIntLabelMapItem other) {
        if (other == StringIntLabelMapItem.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDisplayName()) {
          bitField0_ |= 0x00000004;
          displayName_ = other.displayName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StringIntLabelMapItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StringIntLabelMapItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * String name. The most common practice is to set this to a MID or synsets id.
       * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
       * </pre>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * String name. The most common practice is to set this to a MID or synsets id.
       * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
       * </pre>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * String name. The most common practice is to set this to a MID or synsets id.
       * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * String name. The most common practice is to set this to a MID or synsets id.
       * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
       * </pre>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * String name. The most common practice is to set this to a MID or synsets id.
       * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
       * </pre>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * String name. The most common practice is to set this to a MID or synsets id.
       * Synset: a set of synonyms that share a common meaning. https://en.wikipedia.org/wiki/WordNet
       * </pre>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Integer id that maps to the string name above. Label ids should start from 1.
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Integer id that maps to the string name above. Label ids should start from 1.
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Integer id that maps to the string name above. Label ids should start from 1.
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 2;</code>
       *
       * <pre>
       * Integer id that maps to the string name above. Label ids should start from 1.
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      private Object displayName_ = "";
      /**
       * <code>optional string display_name = 3;</code>
       *
       * <pre>
       * Human readable string label.
       * </pre>
       */
      public boolean hasDisplayName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string display_name = 3;</code>
       *
       * <pre>
       * Human readable string label.
       * </pre>
       */
      public String getDisplayName() {
        Object ref = displayName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            displayName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string display_name = 3;</code>
       *
       * <pre>
       * Human readable string label.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDisplayNameBytes() {
        Object ref = displayName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          displayName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string display_name = 3;</code>
       *
       * <pre>
       * Human readable string label.
       * </pre>
       */
      public Builder setDisplayName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        displayName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string display_name = 3;</code>
       *
       * <pre>
       * Human readable string label.
       * </pre>
       */
      public Builder clearDisplayName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        displayName_ = getDefaultInstance().getDisplayName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string display_name = 3;</code>
       *
       * <pre>
       * Human readable string label.
       * </pre>
       */
      public Builder setDisplayNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        displayName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem)
    }

    static {
      defaultInstance = new StringIntLabelMapItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem)
  }

  public interface StringIntLabelMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    java.util.List<StringIntLabelMapItem>
        getItemList();
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    StringIntLabelMapItem getItem(int index);
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    int getItemCount();
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    java.util.List<? extends StringIntLabelMapItemOrBuilder>
        getItemOrBuilderList();
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    StringIntLabelMapItemOrBuilder getItemOrBuilder(
			int index);
  }
  /**
   * Protobuf type {@code org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMap}
   */
  public static final class StringIntLabelMap extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMap)
      StringIntLabelMapOrBuilder {
    // Use StringIntLabelMap.newBuilder() to construct.
    private StringIntLabelMap(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StringIntLabelMap(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StringIntLabelMap defaultInstance;
    public static StringIntLabelMap getDefaultInstance() {
      return defaultInstance;
    }

    public StringIntLabelMap getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StringIntLabelMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                item_ = new java.util.ArrayList<StringIntLabelMapItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              item_.add(input.readMessage(StringIntLabelMapItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = java.util.Collections.unmodifiableList(item_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              StringIntLabelMap.class, Builder.class);
    }

    public static com.google.protobuf.Parser<StringIntLabelMap> PARSER =
        new com.google.protobuf.AbstractParser<StringIntLabelMap>() {
      public StringIntLabelMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StringIntLabelMap(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<StringIntLabelMap> getParserForType() {
      return PARSER;
    }

    public static final int ITEM_FIELD_NUMBER = 1;
    private java.util.List<StringIntLabelMapItem> item_;
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    public java.util.List<StringIntLabelMapItem> getItemList() {
      return item_;
    }
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    public java.util.List<? extends StringIntLabelMapItemOrBuilder>
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    public StringIntLabelMapItem getItem(int index) {
      return item_.get(index);
    }
    /**
     * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
     */
    public StringIntLabelMapItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }

    private void initFields() {
      item_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(1, item_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, item_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static StringIntLabelMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StringIntLabelMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StringIntLabelMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StringIntLabelMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StringIntLabelMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static StringIntLabelMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static StringIntLabelMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static StringIntLabelMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static StringIntLabelMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static StringIntLabelMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(StringIntLabelMap prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMap)
        StringIntLabelMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                StringIntLabelMap.class, Builder.class);
      }

      // Construct using org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapOuterClass.StringIntLabelMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return StringIntLabelMapOuterClass.internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_descriptor;
      }

      public StringIntLabelMap getDefaultInstanceForType() {
        return StringIntLabelMap.getDefaultInstance();
      }

      public StringIntLabelMap build() {
        StringIntLabelMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public StringIntLabelMap buildPartial() {
        StringIntLabelMap result = new StringIntLabelMap(this);
        int from_bitField0_ = bitField0_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof StringIntLabelMap) {
          return mergeFrom((StringIntLabelMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(StringIntLabelMap other) {
        if (other == StringIntLabelMap.getDefaultInstance()) return this;
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StringIntLabelMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (StringIntLabelMap) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<StringIntLabelMapItem> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          item_ = new java.util.ArrayList<StringIntLabelMapItem>(item_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          StringIntLabelMapItem, StringIntLabelMapItem.Builder, StringIntLabelMapItemOrBuilder> itemBuilder_;

      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public java.util.List<StringIntLabelMapItem> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public StringIntLabelMapItem getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder setItem(
          int index, StringIntLabelMapItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder setItem(
          int index, StringIntLabelMapItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder addItem(StringIntLabelMapItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder addItem(
          int index, StringIntLabelMapItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder addItem(
          StringIntLabelMapItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder addItem(
          int index, StringIntLabelMapItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder addAllItem(
          Iterable<? extends StringIntLabelMapItem> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public StringIntLabelMapItem.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public StringIntLabelMapItemOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public java.util.List<? extends StringIntLabelMapItemOrBuilder>
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public StringIntLabelMapItem.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            StringIntLabelMapItem.getDefaultInstance());
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public StringIntLabelMapItem.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, StringIntLabelMapItem.getDefaultInstance());
      }
      /**
       * <code>repeated .org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMapItem item = 1;</code>
       */
      public java.util.List<StringIntLabelMapItem.Builder>
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          StringIntLabelMapItem, StringIntLabelMapItem.Builder, StringIntLabelMapItemOrBuilder>
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              StringIntLabelMapItem, StringIntLabelMapItem.Builder, StringIntLabelMapItemOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMap)
    }

    static {
      defaultInstance = new StringIntLabelMap(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.springframework.cloud.stream.app.object.detection.protos.StringIntLabelMap)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n)src/main/proto/string_int_label_map.pr" +
      "oto\022<org.springframework.cloud.stream.ap" +
      "p.object.detection.protos\"G\n\025StringIntLa" +
      "belMapItem\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\024\n\014" +
      "display_name\030\003 \001(\t\"v\n\021StringIntLabelMap\022" +
      "a\n\004item\030\001 \003(\0132S.org.springframework.clou" +
      "d.stream.app.object.detection.protos.Str" +
      "ingIntLabelMapItem"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMapItem_descriptor,
        new String[] { "Name", "Id", "DisplayName", });
    internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_springframework_cloud_stream_app_object_detection_protos_StringIntLabelMap_descriptor,
        new String[] { "Item", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
